/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
JparamTestAudioProcessorEditor::JparamTestAudioProcessorEditor (JparamTestAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
  setSize (400, 300);
}

JparamTestAudioProcessorEditor::~JparamTestAudioProcessorEditor()
{
}

//==============================================================================
void JparamTestAudioProcessorEditor::paint (Graphics& g)
{
  g.fillAll (Colours::white);
}

void JparamTestAudioProcessorEditor::resized()
{
}
